# prometheus/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['206.189.239.85:3000'] 

  # Tu trabajo para raspar Node Exporter (si ya lo añadiste al compose)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']