name: CI/CD Pipeline to Cloud Run

on:
  push:
    branches:
      # - main # Despliegue continuo a producción cuando se fusiona en main
      - develop # Despliegue continuo a desarrollo cuando se fusiona en develop
      # - release/* # Opcional: Si usas ramas de release, también podrías desplegar desde aquí
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      # - main # Integración continua para PRs que van a main
      - develop # Integración continua para PRs que van a develop
      # # - feature/* # Opcional: Si quieres ejecutar CI en cada push a ramas feature

# Permisos mínimos requeridos para el workflow.
# 'contents: read' para checkout.
# 'id-token: write' si usas Workload Identity Federation (recomendado para GCP auth).
# 'pull-requests: read' para los triggers de PR.
permissions:
  contents: read # Necesario para actions/checkout
  id-token: write # Necesario para google-github-actions/auth si usas Workload Identity Federation
  pull-requests: read # Importante para los eventos de PR

env: # Variables de entorno globales para el workflow (opcional, pueden ir por job)
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }} # Región de Artifact Registry
  GAR_REPOSITORY: ${{ secrets.GAR_REPOSITORY }} # Nombre del repositorio de Artifact Registry
  CLOUD_RUN_SERVICE_NAME: ${{ secrets.CLOUD_RUN_SERVICE_NAME }} # Nombre del servicio Cloud Run

jobs:
  # Job de Integración Continua: Construir, Testear, Verificar
  ci:
    name: Build and Test
    runs-on: ubuntu-latest # O otro runner si necesitas un SO específico

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Asegúrate de que coincida con la versión en tu Dockerfile

    - name: Install dependencies
      # --production=false instala devDependencies, necesarias para tests y linters
      run: npm install --production=false

    - name: Run Tests
      run: npm test
      env: # <-- Añade este bloque
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/dummy_credentials.json # El valor exacto no importa ya que VertexAI está mockeado
        GOOGLE_CLOUD_PROJECT: dummy-project-id 

  # Job de Despliegue Continuo: Dockerizar, Subir a GAR, Desplegar a Cloud Run
  # Este job SOLO se ejecutará si el job 'ci' pasa y si el trigger es un push a 'main'
  cd:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: ci # Este job depende del job 'ci'. Solo se ejecuta si el CI pasa.
    # Despliega solo en push a la rama 'main' (cambia si tu flujo Gitflow despliega desde otra rama)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # Configuración del entorno de despliegue en GitHub (opcional, para tracking)
    environment:
       name: Production # O Staging, si despliegas a un entorno de pruebas primero
       url: ${{ steps.deploy.outputs.url }} # Enlace a la URL del servicio desplegado

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # --- Autenticación con Google Cloud ---
    - name: Authenticate to Google Cloud
      id: 'auth' # Asigna un ID para referenciar este paso si es necesario
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY_CI_CD }}'

    # --- Configurar Docker ---
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # --- Construir y Etiquetar la imagen Docker ---
    - name: Build and tag Docker image
      run: |
        # Define el nombre completo de la imagen incluyendo el registro, repo y tag (usamos el SHA del commit como tag)
        IMAGE_NAME=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.CLOUD_RUN_SERVICE_NAME }}:${{ github.sha }}
        echo "Building image: $IMAGE_NAME"
        # Construye la imagen usando el Dockerfile en el directorio actual (.)
        docker build . -t $IMAGE_NAME

    # --- Subir la imagen Docker a Google Artifact Registry ---
    - name: Push Docker image
      run: |
        IMAGE_NAME=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.CLOUD_RUN_SERVICE_NAME }}:${{ github.sha }}
        echo "Pushing image: $IMAGE_NAME"
        docker push $IMAGE_NAME

    # --- Desplegar la imagen en Google Cloud Run ---
    - name: Deploy to Cloud Run
      id: deploy # Asigna un ID para poder obtener los outputs (como la URL)
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.CLOUD_RUN_SERVICE_NAME }} # Nombre del servicio en Cloud Run
        region: ${{ env.GAR_LOCATION }} # Región donde desplegar el servicio (normalmente la misma que GAR)
        # La imagen a desplegar es la que acabamos de subir
        image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.CLOUD_RUN_SERVICE_NAME }}:${{ github.sha }}
        # Configura la cuenta de servicio que usará el servicio Cloud Run
        service_account: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}

    # --- Paso: Mostrar la URL del servicio desplegado ---
    # - name: Show deployed URL
    #   run: echo "Servicio ${{ env.CLOUD_RUN_SERVICE_NAME }} desplegado en: ${{ steps.deploy.outputs.url }}"