name: CI/CD Pipeline to Cloud Run

on:
  push:
    branches:
      - main # Despliegue continuo a producción cuando se fusiona en main
      # - develop # Despliegue continuo a desarrollo cuando se fusiona en develop
      # - release/* # Opcional: Si usas ramas de release, también podrías desplegar desde aquí
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      # - main # Integración continua para PRs que van a main
      - develop # Integración continua para PRs que van a develop
      # # - feature/* # Opcional: Si quieres ejecutar CI en cada push a ramas feature

# Permisos mínimos requeridos para el workflow.
# 'contents: read' para checkout.
# 'id-token: write' si usas Workload Identity Federation (recomendado para GCP auth).
# 'pull-requests: read' para los triggers de PR.
permissions:
  contents: read # Necesario para actions/checkout
  id-token: write # Necesario para google-github-actions/auth si usas Workload Identity Federation
  pull-requests: read # Importante para los eventos de PR

env: # Variables de entorno globales para el workflow (opcional, pueden ir por job)
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }} # Región de Artifact Registry
  GAR_REPOSITORY: ${{ secrets.GAR_REPOSITORY }} # Nombre del repositorio de Artifact Registry
  CLOUD_RUN_SERVICE_NAME: ${{ secrets.CLOUD_RUN_SERVICE_NAME }} # Nombre del servicio Cloud Run

jobs:
  # Job de Integración Continua: Construir, Testear, Verificar
  ci:
    name: Build and Test
    runs-on: ubuntu-latest # O otro runner si necesitas un SO específico

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Asegúrate de que coincida con la versión en tu Dockerfile

    - name: Install dependencies
      # --production=false instala devDependencies, necesarias para tests y linters
      run: npm install --production=false

    - name: Run Tests
      run: npm test
      env: # <-- Añade este bloque
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/dummy_credentials.json # El valor exacto no importa ya que VertexAI está mockeado
        GOOGLE_CLOUD_PROJECT: dummy-project-id 

  # Job de Despliegue Continuo: Dockerizar, Subir a GAR, Desplegar a Cloud Run
  # Este job SOLO se ejecutará si el job 'ci' pasa y si el trigger es un push a 'main'
  # Job de Despliegue Continuo vía SSH
  cd:
    name: Deploy via SSH
    runs-on: ubuntu-latest
    needs: ci # Este job depende del job 'ci'. Solo se ejecuta si el CI pasa.
    # Despliega solo en push a la rama 'main' (o la que decidas para producción)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Mantenemos la condición de despliegue a prod

    # Permisos requeridos para el workflow (los mismos que antes, aunque algunos no se usen para SSH)
    permissions:
      contents: read # Necesario para actions/checkout
      # id-token: write # Ya no necesario para GCP auth en este job
      # pull-requests: read # No necesario para este job

    # Variables de entorno para el job CD (credenciales SSH)
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }} # IP del servidor
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }} # Usuario SSH
      # SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }} # <-- PELIGROSO: Usar solo si no puedes usar claves SSH


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # --- Paso 1: Configurar Agente SSH con Clave Privada ---
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.8.0 # Acción para añadir la clave privada al agente SSH
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # Usa el Secret con tu clave privada

    # --- Paso 2: Transferir Archivos al Servidor ---
    # Usaremos scp (Secure Copy) sobre SSH. El agente SSH configurado se usará automáticamente.
    # Necesitas la carpeta de destino en el servidor (ej: /home/appdeployer/my-app)
    - name: Copy files via SCP
      run: |
        # Asegúrate de que el directorio de destino existe en el servidor
        ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "mkdir -p /home/$SSH_USERNAME/my-app"
        # Copia los archivos del repositorio (excepto .git, node_modules si no quieres copiarlos)
        # Puedes necesitar excluir carpetas grandes como node_modules si las instalas en el servidor
        scp -r -o StrictHostKeyChecking=no \
            ./* \
            $SSH_USERNAME@$SSH_HOST:/home/$SSH_USERNAME/my-app/
      # Si usas autenticación por contraseña (NO RECOMENDADO), necesitarías una acción diferente
      # como appleboy/scp-action y pasarle la contraseña, lo cual es INSEGURO.

    # --- Paso 3: Instalar Dependencias en el Servidor ---
    # Ejecuta npm install en el servidor vía SSH
    - name: Install dependencies on server
      uses: appleboy/ssh-action@v1.0.3 # Acción para ejecutar comandos SSH
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }} # Usa la clave privada para autenticar
        # password: ${{ env.SSH_PASSWORD }} # <--- PELIGROSO: Usar solo si no hay clave SSH
        script: |
          cd /home/${{ env.SSH_USERNAME }}/my-app
          npm install --production # Instala solo las dependencias de producción

    # --- Paso 4: Reiniciar la Aplicación en el Servidor (usando PM2) ---
    # Ejecuta comandos de PM2 vía SSH
    - name: Restart application on server (PM2)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }} # Autenticación
        # password: ${{ env.SSH_PASSWORD }} # <--- PELIGROSO
        script: |
          cd /home/${{ env.SSH_USERNAME }}/my-app
          pm2 start server.js --name my-app --update-env || pm2 restart my-app --update-env
          pm2 save
      # Asegúrate de que PM2 está instalado globalmente en el servidor y configurado para el usuario SSH

    # Puedes añadir pasos adicionales si usas systemd en lugar de PM2
    # - name: Restart application on server (systemd)
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: ${{ env.SSH_HOST }}
    #     username: ${{ env.SSH_USERNAME }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script: |
    #       # Necesitarás configurar sudo sin contraseña para el usuario deployer
    #       # si systemctl requiere sudo
    #       sudo systemctl restart my-app.service


    # --- Eliminar el paso de despliegue a Cloud Run ---
    # - name: Deploy to Cloud Run # <-- Eliminar este paso
    #   ...


    # --- Paso Opcional: Mostrar mensaje de éxito ---
    - name: Deployment Successful
      run: echo "Despliegue a ${{ env.SSH_HOST }} completado para la versión ${{ github.sha }}"